# Generated by Django 6.0 on 2026-01-10 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_profile_created_organization_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_organizations",
                to="accounts.profile",
            ),
        ),
    ]
