# Generated by Django 6.0.2 on 2026-02-28 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_invitationtoken'),
        ('accounts', '0005_default_basic_plan'),
    ]

    operations = [
    ]
