# Generated by Django 6.0 on 2026-01-07 10:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestedContent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                (
                    "content_type",
                    models.CharField(
                        choices=[("file", "File"), ("url", "URL")], max_length=10
                    ),
                ),
                (
                    "data_url",
                    models.CharField(
                        help_text="Local file path or external URL", max_length=1000
                    ),
                ),
                ("chunk_count", models.PositiveIntegerField(default=0)),
                (
                    "ingestion_status",
                    models.CharField(default="pending", max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contents",
                        to="accounts.organization",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_contents",
                        to="accounts.profile",
                    ),
                ),
            ],
        ),
    ]
