# Generated by Django 6.0 on 2026-01-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_systemsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="persona_prompt_map",
            field=models.JSONField(
                default=dict,
                help_text="Mapping of persona combinations to generated system prompts",
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="system_prompt",
            field=models.TextField(
                help_text="Resolved system instruction used for RAG / chat responses"
            ),
        ),
    ]
