# Generated by Django 6.0 on 2026-01-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_systemsettings_persona_prompt_map_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemsettings",
            name="persona_prompt_map",
            field=models.JSONField(
                default=dict,
                help_text="Mapping of persona name to generated system prompt",
            ),
        ),
    ]
