# Generated by Django 6.0 on 2026-01-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0005_alter_systemsettings_persona_prompt_map"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemsettings",
            name="persona_prompt_map",
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="personas",
            field=models.JSONField(
                default=list, help_text="List of personas used to generate this prompt"
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="system_prompt",
            field=models.TextField(
                help_text="System instruction used for RAG / chat responses"
            ),
        ),
    ]
