# Generated by Django 6.0.2 on 2026-02-12 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_organization_owner'),
        ('project', '0007_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='role',
            field=models.CharField(default='Support Agent', help_text='Role of the agent (e.g. Support Agent, Sales Agent)', max_length=255),
        ),
        migrations.AddField(
            model_name='agent',
            name='system_prompt',
            field=models.TextField(blank=True, help_text='Custom system prompt for this agent', null=True),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_settings', to='accounts.organization'),
        ),
    ]
