# Generated by Django 6.0.2 on 2026-02-12 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_organization_owner'),
        ('project', '0008_agent_role_agent_system_prompt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_settings', to='accounts.organization'),
        ),
    ]
