# Generated by Django 6.0.2 on 2026-02-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_convert_role_to_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='role',
            field=models.JSONField(blank=True, default=list, help_text="List of roles/personas for the agent (e.g. ['Support Agent', 'Sales Agent'])"),
        ),
    ]
