# Generated by Django 5.2.11 on 2026-03-15 06:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alter_agent_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('theme_color', models.CharField(max_length=100, null=True)),
                ('is_embedded', models.BooleanField(default=False)),
                ('chatbot_dimension', models.JSONField(default=list, null=True)),
                ('text_colour', models.CharField(default='#00000099', max_length=100, null=True)),
                ('header_color', models.CharField(default='#070706', max_length=100, null=True)),
                ('header_text_color', models.CharField(default='white', max_length=100, null=True)),
                ('collecting_leads', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='project.agent')),
            ],
        ),
    ]
